config/routes.rb
Rails.application.routes.draw do

  root "homepages#home"

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :videos do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  get "/login", to: "sessions#new"

  get "/homepage", to: "homepages#home"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :author, class_name: "User", foreign_key: "author_id"
  belongs_to :video

  has_attached_file :videoupload, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :videoupload, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :videos
  has_many :comments

  has_secure_password

  validates :username, presence:true, uniqueness: true, length: { maximum: 30}
  validates :email, presence:true, uniqueness: true
end

app/models/video.rb
class Video < ActiveRecord::Base

  belongs_to :user
  has_many :comments

  validates :video_link, uniqueness: true, presence: true, length: { is: 11 }
  validates :title, presence: true, length: { maximum: 30}
  validates :filmed_where, presence: true, length: { maximum: 24}

  def vine_link
    "https://vine.co/v/#{self.video_link}"
  end

  def embed_link
    "https://vine.co/v/#{self.video_link}/embed/simple"
  end

  def self.iterate_every(step, starting=0)
   every = all
   total = every.length - 1
   (starting..total).step(step) { |i| yield every[i] }
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



  private
    # Make the current_user method available to views, not just controllers!
    helper_method :current_user, :is_on_homepage

    def current_user
      @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

      def authorize
      redirect_to login_path, alert: 'Not authorized - you must be logged in!' if current_user.nil?
    end

    #def current_comment
     # @current_comment ||= User.find(session[:user_id]) if session[:user_id]
    #end

    def is_on_homepage
      params[:controller] == "homepages" && params[:action] == "home"
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # def index
  #   if params[:video_id]
  #     @video = Video.find(params[:video_id])
  #     @comments = @video.comments
  #   else
  #     comments = Comment.all
  #   end
  # end

  # def new
  #   @video = Video.find(params[:video_id])
  #   @comment = Comment.new
  # end

  # def show

  #   end

  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    @comment.video_id = params[:video_id]
    if @comment.save
      flash[:notice] = "You've added a comment!"
      redirect_to video_path(params[:video_id])
    else
      render videos_path
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to  video_path(@comment.video)
    else
      render :edit
    end
   end


  def destroy
    if params[:video_id]
      # if destroy is nested in a video, we will assume this means
      # remove the tag from the video, not "DESTROY tag"…
      video = Video.find params[:video_id]
      comment = Comment.find params[:id]
      comment.delete
      redirect_to video_path(video)
      end
  end

  def comment_params
      params.require(:comment).permit(:message, :videoupload)
  end

end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController


  def home
    render  :homepage => "homepage"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to videos_path, notice: "You are logged in"
    else
      flash.now.alert = 'Invalid login credentials - try again!'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to videos_path, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @videos = current_user.videos
  end

  def create
    @user = User.new (user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:alert] = "You have successfully signed up!"
      redirect_to videos_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
    @videos = Video.all
  end

  def show
    @video = Video.find(params[:id])
    @comment = Comment.new
  end

  def new
    if current_user.present?
    @video = Video.new
    else
      redirect_to videos_path
    end
  end

  def create
    @video = Video.new(self.video_params)
    @video.user = current_user
    if @video.save
      redirect_to videos_path
    else
      render :new
    end
  end

  def edit
    @video = Video.find(params[:id])
    if  @video.user != current_user
      redirect_to videos_path
    end
  end

  def update
    @video = Video.find(params[:id])
    if @video.update(self.video_params)
      redirect_to  video_path
    else
      render :edit
    end
  end

   def destroy
    @video = Video.find(params[:id])
    @video = @video.destroy
    flash[:message] = "'#{@video.title}' removed!"
    redirect_to videos_path
   end


    def video_params
      params.require(:video).permit(:title, :tags, :video_link, :filmed_when, :filmed_where)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/comments/edit.html.erb
<%= bootstrap_form_for [@comment.video, @comment] do |f| %>

  <%= f.text_area :message %>
  <%= f.file_field :videoupload %>
  <%= f.submit "Save" %>
<% end %>

app/views/homepages/home.html.erb
<!-- <video class = "homepage" autoplay poster="http://www.hdwallpapersnew.net/wp-content/uploads/2015/12/beautiful-landscape-high-resolution-new-best-pictures-download-free.jpg" id="bgvid" loop>
 -->

<%= video_tag("best.mp4", class: "homepage",  autoplay: true, loop: true)%>

<p class="homepage_text"><%= link_to "InstaVid", videos_path%></p>

app/views/layouts/application.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

<!DOCTYPE html>
<html>
<head>
  <link rel="icon" href="https://i.imgur.com/C271WhY.png">
    <title>InstaVid</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
</head>


<body>

<% if ! is_on_homepage %>
  <header>
    <h1 id="header_id">InstaVid</h1>
  </header>

  <%if current_user %>
    <nav>
      <%= link_to "Add Video", new_video_path %> &nbsp;|&nbsp;
      <%= link_to "Your Videos", user_path(current_user) %>
    </nav>
    <ul class = "nav nav-pills nav-justified">
      <li>

        <span class="glyphicon glyphicon-home"></span>
        <%=link_to "Home", videos_path%>
      </li>
      <li>
        <span class="glyphicon glyphicon-remove-sign"></span>
        <%= link_to 'Log Out', session_path('dummy'), method: :delete %>
      </li>
    </ul>
  <% end %>
<% end %>



<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<ul class = "nav nav-pills nav-justified">
  <li><span class="glyphicon glyphicon-home"></span><%= link_to 'Home', videos_path %></li>
  <li> <span class="glyphicon glyphicon-ok-circle"></span><%= link_to 'Log in', login_path %></li>
</ul>

<div class="form-container">

<%= bootstrap_form_for @user do |f| %>
  <%= f.text_field :username %>
  <%= f.text_field :email %>
  <%= f.password_field :password%>
  <%= f.password_field :password_confirmation%>
  <%=f.submit "Submit"%>
<% end %>
</div>

app/views/users/show.html.erb
<h3><%= current_user.username %>'s Account</h3>

<div class="col-md-3">
  <% @videos.iterate_every(4) do |video| %>
    <div class="simple_user">
    <h4><%= link_to video.title, video %>
    <br>
    <%= "(#{video.filmed_where})" %></h4>
    <iframe width="290" height="350" src="<%= video.embed_link %>" frameborder="0" allowfullscreen></iframe>
    <br>
    <span><%= video.tags %></span>&nbsp;
    <span>(<%= video.filmed_when%>)</span>

    <div class = "controls">
      <% if current_user %>
        <span><%= link_to "Edit", edit_video_path(video) %> </span>
        | <span><%= link_to "Remove", video_path(video.id), method: "DELETE",
        data: {confirm: "Are you sure you want to delete this video?"} %> </span>|
        <span><%=link_to "Comment", video_path(video)%></span>
  <% end %>
     </div>
   </div>
      <% end %>
</div>

<div class="col-md-3">
      <% @videos.iterate_every(4,1) do |video| %>
      <div class="simple_user">
      <h4><%= link_to video.title, video %>
      <br>
       <%= "(#{video.filmed_where})" %></h4>
      <iframe width="290" height="350" src="<%= video.embed_link %>" frameborder="0" allowfullscreen></iframe>
        <br>
      <span><%= video.tags %></span>&nbsp;
      <span>(<%= video.filmed_when%>)</span>
  <div class = "controls">
    <% if current_user %>
     <span><%= link_to "Edit", edit_video_path(video) %> </span>
    | <span><%= link_to "Remove", video_path(video.id), method: "DELETE",
     data: {confirm: "Are you sure you want to delete this video?"} %> </span>|
     <span><%=link_to "Comment", video_path(video)%></span>
    <% end %>
   </div>
   </div>
      <% end %>
</div>

 <div class="col-md-3">
      <% @videos.iterate_every(4,2) do |video| %>
      <div class="simple_user">
      <h4><%= link_to video.title, video %>
      <br>
      <%= "(#{video.filmed_where})" %></h4>
      <iframe width="290" height="350" src="<%= video.embed_link %>" frameborder="0" allowfullscreen></iframe>
        <br>
      <span><%= video.tags %></span>&nbsp;
      <span>(<%= video.filmed_when%>)</span>
  <div class = "controls">
    <% if current_user %>
     <span><%= link_to "Edit", edit_video_path(video) %> </span>
    | <span><%= link_to "Remove", video_path(video.id), method: "DELETE",
     data: {confirm: "Are you sure you want to delete this video?"} %> </span>|
     <span><%=link_to "Comment", video_path(video)%></span>
    <% end %>
   </div>
   </div>
      <% end %>
</div>

 <div class="col-md-3">
      <% @videos.iterate_every(4,3) do |video| %>
      <div class="simple_user">
      <h4><%= link_to video.title, video %>
      <br>
      <%= "(#{video.filmed_where})" %></h4>
      <iframe width="290" height="350" src="<%= video.embed_link %>" frameborder="0" allowfullscreen></iframe>
        <br>
      <span><%= video.tags %></span>&nbsp;
      <span>(<%= video.filmed_when%>)</span>
  <div class = "controls">
    <% if current_user %>
     <span><%= link_to "Edit", edit_video_path(video) %> </span>
   | <span><%= link_to "Remove", video_path(video.id), method: "DELETE",
     data: {confirm: "Are you sure you want to delete this video?"} %> </span>|
     <span><%=link_to "Comment", video_path(video)%></span>
    <% end %>
   </div>
   </div>
      <% end %>
</div>

app/views/videos/_form.html.erb
<div class="form-container">
<%= bootstrap_form_for @video, html: { multipart: true } do |f| %>
  <%= f.text_field :title %>
  <%= f.text_field :tags, label: "#Tags" %>
  <%= f.text_field :video_link, label: "Vine ID" %>
  <%= f.date_select :filmed_when, order: [:month, :day, :year] %>
  <%= f.text_field :filmed_where %>
  <%= f.submit "Submit" %>
<% end %>
</div>

<ul>
<% @video.errors.full_messages.each do |message| %>
  <li><%= message %></li>
<% end %>
</ul>

app/views/videos/edit.html.erb
<%= render "form" %>

app/views/videos/index.html.erb
<ul class = "nav nav-pills nav-justified">
<% if current_user %>
  <p class = "welcome">
  Welcome, <%=link_to current_user.username, user_path(current_user)%>
  </p>

<% else %>
  <li>
  <span class="glyphicon glyphicon-ok-circle"></span><%= link_to 'Log In', login_path %>
  </li>

  <li>
  <span class="glyphicon glyphicon-heart-empty"></span><%= link_to 'Sign Up', new_user_path %>
  </li>
<% end %>
</ul>





<div class="col-sm-6 col-md-4 video-container">
      <% @videos.iterate_every(3) do |video| %>
      <div class="simple">

      <h4><%= link_to video.title, video %>
      <br>
       <%= "(#{video.filmed_where})" %></h4>
      <iframe width="290" height="350" src="<%= video.embed_link %>" frameborder="0" allowfullscreen></iframe>
      <br>

      <span><%= video.tags %></span> &nbsp;
      <span>(<%= video.filmed_when%>)</span>

  <div class = "controls">

  <% if current_user %>
    <%=link_to "Comment", video_path(video) + "#comment_message"%>
  <%end%>
    <% if video.user == current_user %>
     | <span><%= link_to "Edit", edit_video_path(video) %> </span>|
     <span><%= link_to "Remove", video_path(video.id), method: "DELETE",
     data: {confirm: "Are you sure you want to delete this video?"} %> </span>
    <% end %>
   </div>
   </div>
      <% end %>
</div>

<div class="col-sm-6 col-md-4 video-container">
      <% @videos.iterate_every(3,1) do |video| %>
      <div class="simple">
      <h4><%= link_to video.title, video %>
        <br>
      <%= "(#{video.filmed_where})" %></h4>
      <iframe width="290" height="350" src="<%= video.embed_link %>" frameborder="0" allowfullscreen></iframe>
        <br>
    <span><%= video.tags %></span> &nbsp;
      <span>(<%= video.filmed_when%>)</span>
  <div class = "controls">
  <% if current_user %>
    <%=link_to "Comment", video_path(video) + "#comment_message" %>
  <%end%>
      <% if video.user == current_user %>
     | <span><%= link_to "Edit", edit_video_path(video) %> </span>|
     <span><%= link_to "Remove", video_path(video.id), method: "DELETE",
     data: {confirm: "Are you sure you want to delete this video?"} %> </span>
    <% end %>
   </div>
   </div>
      <% end %>
</div>

<div class="col-sm-6 col-md-4 video-container">
      <% @videos.iterate_every(3,2) do |video| %>
      <div class="simple">
      <h4><%= link_to video.title, video %>
        <br>
      <%= "(#{video.filmed_where})" %></h4>
      <iframe width="290" height="350" src="<%= video.embed_link %>" frameborder="0" allowfullscreen></iframe>
        <br>
     <span><%= video.tags %></span> &nbsp;
      <span>(<%= video.filmed_when%>)</span>
  <div class = "controls">
  <% if current_user %>
    <%=link_to "Comment", video_path(video) + "#comment_message"%>
  <%end%>
      <% if video.user == current_user %>
      | <span><%= link_to "Edit", edit_video_path(video) %> </span>|
     <span><%= link_to "Remove", video_path(video.id), method: "DELETE",
     data: {confirm: "Are you sure you want to delete this video?"} %> </span>
    <% end %>
   </div>
   </div>
      <% end %>
</div>

app/views/videos/new.html.erb
<%= render "form" %>

app/views/videos/show.html.erb
<main>
  <article class= "simple video_show">
    <h4><%= link_to @video.title, @video.vine_link %></h4>
    <p><strong>Posted by: </strong><%= @video.user.username %></p>
    <iframe id="videoPlayer" width="600" height="600" src="<%= @video.embed_link %>" frameborder="0" allowfullscreen></iframe>
    <br>
    <span class= "video_span"><%= @video.tags %></span> |
    <span class= "video_span"><%= @video.filmed_when%></span> |
    <span class= "video_span"><%= @video.filmed_where%></span>
    <br>
    <% if @video.user == current_user%>
    <div class = "controls">
      <span><%= link_to "Edit", edit_video_path(@video) %> </span> &nbsp; | &nbsp;
      <span><%= link_to "Remove", video_path(@video.id), method: "DELETE",
      data: {confirm: "Are you sure you want to delete this video?"} %> </span>
    </div>
    <%end%>
  </article>

<% @video.comments.each do |comment| %>

  <article class = "simple_comment">
    <% if comment.videoupload.present? %>
        <p><strong>Comment by: </strong><%= comment.author.username %></p>
        <p><%= image_tag comment.videoupload.url(:medium) %></p>
        <p><%= comment.message %></p>

    <% else %>
        <p><strong>Comment by: </strong><%= comment.author.username %></p>
        <p><%= comment.message %></p>
        <% end %>

          <% if comment.author == current_user %>
          <%= link_to "Edit", edit_video_comment_path(@video, comment) %> &nbsp; | &nbsp;
          <%= link_to "Remove", video_comment_path(@video, comment), method: "DELETE", data: {confirm: "Are you sure you want to delete this comment?"} %>
        <% end %>
  </article>
    <% end %>

 <%= form_for [@video, @comment] do |f| %>
  <article class= "post_comment">
  <%= f.text_area :message %>
  <br>
  <%= f.label :videoupload, "Upload Photo" %>
  <article class= "comeon"><%= f.file_field :videoupload %></article>
  <%= f.submit "Post Comment" %>
  <% end %>
  </article>

</main>
<!--
<script src="https://www.Vine.com/iframe_api"></script>
<script>
  var player;
  function onVineIframeAPIReady() {
    player = new YT.Player('videoPlayer', {
      events: {
        'onReady': function(evt) { console.log('video is ready to play', evt)},
        'onStateChange': function(evt) {
          console.log('state changed: ', evt);
        }
      }
    });
    console.dir(player);
  }
</script>
 -->